## **Matrix and Its Operations**

In [1]:
import numpy as np
#Matrix Given
vectorA = np.array([[-5,0],[4,1]])
vectorB = np.array([[6,-3],[2,3]])

#Operations
sum         = vectorA + vectorB
difference1 = vectorB - vectorA
difference2 = vectorA - vectorB

#Output
print(64*'#')
print('The sum of vectorA + VectorB is equal to:\n',sum)
print(64*'#')
print('The difference of vectorB + VectorA is equal to:\n',difference1)
print(64*'#')
print('The difference of vectorA + VectorB is equal to:\n',difference2)
print(64*'#')

################################################################
The sum of vectorA + VectorB is equal to:
 [[ 1 -3]
 [ 6  4]]
################################################################
The difference of vectorB + VectorA is equal to:
 [[11 -3]
 [-2  2]]
################################################################
The difference of vectorA + VectorB is equal to:
 [[-11   3]
 [  2  -2]]
################################################################
